language: node_js
node_js:
  - "8.11.1"
cache:
  directories:
  - node_modules
script:
  - npm run docs
before_deploy:
  - npm run test:coveralls || travis_terminate 1
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file: release.zip
    on:
      tags: true
after_deploy:
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $cws_client_id $cws_client_secret $cws_token ./release.zip $extension_id;
    fi
