language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
after_success:
  - npm run report-coverage